### ISSUE TITLE
Documentation: aliases missing

### ISSUE THREAD

**Issue by mikebridge** [single-spa/import-map-deployer#32]
The documentation shows that an alias can be created to set a default environment but it the syntax is missing from the documentation.

I would like to change my current setup to make `prod` the default but I'm not sure how to do it:

```json
{
    "manifestFormat": "importmap",
    "locations": {
        "prod": "google://my-bucket/prod-import-map.json",
        "staging": "google://my-bucket/staging-import-map.json",
        "dev": "google://my-bucket/dev-import-map.json"
    },
    ...
}
```

**Comment by joeldenning** [comment]
You can change the default env by adding `default` to the locations object:

```json
{
    "manifestFormat": "importmap",
    "locations": {
        "default": "google://my-bucket/prod-import-map.json",
        "prod": "google://my-bucket/prod-import-map.json",
        "staging": "google://my-bucket/staging-import-map.json",
        "dev": "google://my-bucket/dev-import-map.json"
    }
}
```

See related code:

https://github.com/single-spa/import-map-deployer/blob/ee8baee76114e327989e90d3f99bd0b6c9946476/src/web-server.js#L41-L47

This is documented [here](https://github.com/single-spa/import-map-deployer#option-1-json-file) - if there's a different area of the documentation that was unclear/confusing, please send a PR so that others don't get tripped up on the same thing.
