### ISSUE TITLE
Can't host import map inside a folder in google cloud storage

### ISSUE THREAD

**Issue by anas1409** [single-spa/import-map-deployer#99]
Import map deploy doesn't support a path like gs://bucketname/prod/importmap.json. It throws a 404 error and dies.

But it works when file is hosted directly inside the bucket.

![image](https://user-images.githubusercontent.com/55309149/111308285-ec5fe280-8673-11eb-9e1f-4dcda2f2c88c.png)

**Comment by joeldenning** [comment]
It looks like the problem is related to this regex:

https://github.com/single-spa/import-map-deployer/blob/585b24120846a7f70b00588c9e555b3158ec2a97/src/io-methods/google-cloud-storage.js#L5

It tries to capture the bucket name separately from the object key, but fails to do so because the first `.+` is greedy in the regex, but should be lazy. I'll put together a pull request with the fix

**Comment by joeldenning** [comment]
Fix is released in https://github.com/single-spa/import-map-deployer/releases/tag/v4.0.1

**Comment by anas1409** [comment]
@joeldenning Many Thanks!
